# Docs at http://goreleaser.com
builds:
  - id: watcher
    main: ./cmd/watcher/main.go
    binary: watcher
    env:
      - CGO_ENABLED=0
archives:
  - # Default archive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
